# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-10 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('birthday', models.CharField(max_length=20)),
                ('birthplace', models.CharField(max_length=255)),
                ('constellation', models.CharField(max_length=255)),
                ('family_member', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=2)),
                ('image_url', models.CharField(max_length=255)),
                ('other_chinese_name', models.CharField(max_length=255)),
                ('other_english_name', models.CharField(max_length=255)),
                ('profession', models.CharField(max_length=255)),
                ('introduction', models.TextField()),
            ],
            options={
                'db_table': 'actors',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_id', models.CharField(max_length=7)),
                ('user_id', models.IntegerField()),
                ('bengindate', models.CharField(max_length=10)),
                ('persent', models.FloatField(default=0)),
                ('content', models.TextField()),
                ('feather_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='MA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actiorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='douban.Actors')),
            ],
            options={
                'db_table': 'ma',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=255)),
                ('durations', models.CharField(max_length=255)),
                ('writers', models.CharField(max_length=255)),
                ('countries', models.CharField(max_length=255)),
                ('languages', models.CharField(max_length=255)),
                ('genres', models.CharField(max_length=255)),
                ('episodes', models.IntegerField(default=1)),
                ('pubdates', models.CharField(max_length=50)),
                ('directors', models.CharField(max_length=50)),
                ('other_names', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('average', models.FloatField()),
                ('reviews_count', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'movie',
            },
        ),
        migrations.AddField(
            model_name='ma',
            name='movieid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='douban.Movie'),
        ),
        migrations.AddField(
            model_name='actors',
            name='movie',
            field=models.ManyToManyField(through='douban.MA', to='douban.Movie'),
        ),
    ]
